### ISSUE TITLE
I'd like to be able to define kubernetes resources config for test jobs

### ISSUE THREAD

**Issue by nishaad78** [Zooz/predator#336]
**Is your feature request related to a problem? Please describe.**
Currently this is the only resources config set by default for a k8s `Job`:
```yaml
        resources:
          requests:
            cpu: "1"
``` 
I would want more control over this so that I can specify requests and limits, especially on memory. 
This is so that a rogue test run won't accidentally affect other workloads running on the k8s node.

**Describe the solution you'd like**
A way to specify resources config for my Tests, ideally, when creating a Test.
